### PR TITLE
added specific terms for SILAC and metabolic label

### PR DESCRIPTION
**Pull request by ypriverol**

### CODE REVIEW

**Comment by StSchulze** [comment]
There is some inconsistency in the term names, since they sometimes include the isotope composition (e.g. "SILAC heavy L: 13C(6)") and sometimes not (e.g. "SILAC light R")
In principle I would be in favor of including the composition, but I also understand and am fine with keeping the name as short as possible.
The description/comment should be more explicit though, especially in the case of the latter, e.g.:

> name: SILAC heavy R
> comment: The heavy amino acid arginine used in SILAC experiments, using the following isotope: 13C(6)15N(4)

**Comment by ypriverol** [comment]
Fixed the name problem of the names.

**Comment by StSchulze** [comment]
Addition:
There are more SILAC versions out there than what is included based on my proposal (I think the ones here are the most common ones, so others can be added later on if needed, in my opinion), which would be an argument for including the isotope composition in the term name, since there can be different "SILAC heavy R" versions.

**Comment by ypriverol** [comment]
While I understand the idea of including the formula as I said we should try to keep the simplicity.

**Comment by StSchulze** [comment]
I can see that, I'm just trying to plan for the future. How would you include e.g. this one then:
SILAC heavy R: D(8)

**Comment by ypriverol** [comment]
Yes, got it in some cases we can include the formula is are more strange or frequent cases. for differentiation.

**Comment by ypriverol** [comment]
Should we accept the PR and adapt new labels in the future when new labels are needed? @StSchulze

**Comment by StSchulze** [comment]
I think the names should be consistent in order to not be confusing, so if at some point something like `SILAC heavy R: D(8)` is introduced, then the current `SILAC heavy R` should be changed to something like `SILAC heavy R: 13C(6)15N(4)`. If that's easy to do, then sure, go ahead and keep it simple for now. If backwards compatibility is more desirable, then I would say go for the more universal/explicit version.

**Comment by ypriverol** [comment]
I'm thinking we can put in the future other notation like `SILAC heavy R D8`

**Comment by StSchulze** [comment]
Yes, but it introduces an inconsistency that is confusing and can lead to misannotations.

If in the future there are multiple `SILAC heavy R` terms, people will use the simple `SILAC heavy R` even if they mean `SILAC heavy R D8`, e.g. because they haven' seen the other term or don't know exactly what version of heavy R was used and think `SILAC heavy R` is the general term.

**Comment by ypriverol** [comment]
My point is that this term `SILAC heavy R: 13C(6)15N(4)` is quite difficult for an annotator to be pick

**Comment by foellmelanie** [comment]
I am in favour with @StSchulze to also include the full composition in addition to the name. If the next SILAC annotations all go wrong because of that one can still discuss...but I think it will be doable.

**Comment by StSchulze** [comment]
> 
> My point is that this term `SILAC heavy R: 13C(6)15N(4)` is quite difficult for an annotator to be pick

I don't think it's more difficult to pick `SILAC heavy R: 13C(6)15N(4)` than it is to differentiate between `SILAC heavy R` and `SILAC heavy R: D(8)`, rather the opposite.

**Comment by ypriverol** [comment]
My point is that as characteristics, the label is intended to be manually annotated most of the time. The label is quite complex for an annotation. I actually really love your first approach to come with a simple name that contains the type of the label and the target amino acid, if we add the formula is really good for the tools but really complex for manual annotations. It also contains `()`, numbers, etc. The objective of the term is to encode this complex naming into a term that people can pick quickly.

**Comment by foellmelanie** [comment]
What about using amino acid plus weight gain e.g. SILAC K4, SILAC K6, SILAC K8 etc ? This information the user should know exactly because it has to be used for the search....

**Comment by StSchulze** [comment]
> My point is that as characteristics, the label is intended to be manually annotated most of the time. The label is quite complex for an annotation. I actually really love your first approach to come with a simple name that contains the type of the label and the target amino acid, if we add the formula is really good for the tools but really complex for manual annotations. It also contains `()`, numbers, etc. The objective of the term is to encode this complex naming into a term that people can pick quickly.

Hmm, maybe that's a general misunderstanding that I have about the concept of the annotations and feel free to move this into the proteomics-metadata-standard repo if this goes too much into detail for the purpose here. But if I annotate a project and I have to use ontology terms, then I have to look up (or ideally select from a list) the exact term anyway, no matter what it is, because there's no way I will remember if it's `SILAC heavy R` or `heavy SILAC R` or `SILAC heavy Arg`, etc. So if I have to look it up anyway, I'll see the options and can select the one that fits, even if it's complex. But maybe that's just me.


 
> What about using amino acid plus weight gain e.g. SILAC K4, SILAC K6, SILAC K8 etc ? This information the user should know exactly because it has to be used for the search....

I like this, the only drawback is that there are label versions that have the same weight gain (e.g. K D(8) and K 13C(6)N(2)) but the number of these edge cases should be small enough to justify the simplification.

**Comment by levitsky** [comment]
I have no experience with metabolic labeling, this is just my two cents as a passer-by:

I think unambiguous term names are paramount to having usable, correct annotations. Convenience during annotation is secondary, and I think it can be achieved through good annotator tools instead of manual typing of annotations. (Basically, my thinking is the same as @StSchulze's above.) Convenience should not come at the price of ambiguity or inconsistency.

If using weight gain allowed to unambiguously identify the label, it would be a great approach (except I would suggest writing it as `SILAC K+4` etc.). But as @StSchulze points out, it's not unambiguous. Here's a paper where two different +8 SILAC labels (as well as two isotopically different dimethyl labels) are used in the same experiment: https://pubmed.ncbi.nlm.nih.gov/28872844/. Isotopic formulas would be the only way to annotate that experiment in a self-sufficient way.

Also, forgive me if the questions are dumb, but:
1. Is it correct to refer to "reagent" in term descriptions? Or is it better to rephrase them to "labeling method" or something?
2. Does it make sense to have all the different "light" labels if they all just refer to cell growth in normal medium?

**Comment by StSchulze** [comment]
Just to try to answer the questions:

>     1. Is it correct to refer to "reagent" in term descriptions? Or is it better to rephrase them to "labeling method" or something?

I guess technically it is a "reagent" that is bought and added to the medium, but I agree a different phrasing would probably be more intuitive. My suggestion above was
"The heavy amino acid arginine used in SILAC experiments ..."
 
>     2. Does it make sense to have all the different "light" labels if they all just refer to cell growth in normal medium?

It depends on the experiment. At least in microbiology it is fairly common to have knockout mutants for the corresponding pathway that synthesizes the amino acid. So it's not using the "normal" media with a general  N source, but a specifically added amino acid. The isotope distribution of the light version (e.g. ideally >99% 12C) might also differ from the natural isotope (e.g. 99% 12C, 1% 13C) but I'm not exactly sure if that's commonly the case.

**Comment by ypriverol** [comment]
Hi, @StSchulze @foellmelanie @levitsky @lisavetasol I have added all the formula to the label. Let me know if you are ok to merge the PR.

**Comment by StSchulze** [comment]
Little typo (my bad in my initial proposal):
`using the following isotope:` should be either `using the following isotopes:` or `using the following isotope composition:` 
And I'm not sure if the "creation_date" should be changed.
Besides that I think it looks good :)

**Comment by ypriverol** [comment]
Typo fixed.

**Comment by ypriverol** [comment]
Type foxed @StSchulze let me know if you are ok with this to merge the PR.

**Comment by StSchulze** [comment]
Yes, fine with me

**Pull request merged**
