### PR TITLE
Added terms for TMT16plex

### PR DESCRIPTION
**Pull request by ypriverol**

### CODE REVIEW

**Comment by ostr0103** [comment]
Hi Yasset,

I went to submit my SDRF with the 133N, 133C and 134N labels and it still
says "invalid SDRF file detected".  The error in the log submission is as
follows for each of the 3 labels ERROR : Value is not match with ontology',
value='tmt133n', row=111, column='comment[label].  I checked the OLS PRIDE
controlled vocabulary, and it doesn't show up in the system yet. Is there
something I need to do?

Thanks,
Danelle

**Comment by ypriverol** [comment]
@ostr0103 OLS needs to index the ontology. This will happen by the end of the week.

**Comment by ostr0103** [comment]
Excellent, thank you!  I will revisit my submission next week then.

**Comment by ostr0103** [comment]
Hi Yasset,

It looks like the ontology has not been indexed yet.  Do you know if there is a way I can contact OLS?  

Thank you,
Danielle

**Pull request merged**
